library(Matrix)
library(NMF)
library(dplyr)
library(tidyr)
library(devtools)
#library(TxDb.Hsapiens.UCSC.hg19.knownGene)
#library(TxDb.Hsapiens.UCSC.hg38.knownGene)
#library(org.Hs.eg.db)

library(pheatmap)
library(ggplot2)
#library(Seurat)
library(stringr)
library(Rtsne)
library(uwot)
library(mclust)
library(biomaRt)
library(cowplot)
library(ggplotify)
library(RColorBrewer)
library(minerva)
library(preprocessCore)
library(RcppHungarian)

library(data.table)
library(mixdist)
library(mixtools)
library(GenomicRanges)
library(IRanges)

library(readxl)
library(tibble)
library(plyr)
library(gplots)
library(shiny)
library(heatmaply)
library(RColorBrewer)
library(Hmisc)
library(ComplexHeatmap)
library(circlize)
library(lsa)
#use_package("NMF", min_version = '0.21.0')
#use_package("ggplot2", min_version = '3.2.1')
